- name: Ensure certbot directory exists
  ansible.builtin.file:
    path: /opt/certbot
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Ensure secrets directory exists
  ansible.builtin.file:
    path: /opt/certbot/secrets
    state: directory
    owner: root
    group: root
    mode: '700'

- name: Copy Cloudflare credentials
  ansible.builtin.copy:
    src: ../vars/cloudflare.ini
    dest: /opt/certbot/secrets/certbot/cloudflare.ini
    owner: root
    group: root
    mode: '600'

- name: Deploy docker-compose.yml for Certbot
  ansible.builtin.copy:
    src: ../files/docker-compose.yml
    dest: /opt/certbot/docker-compose.yml
    owner: root
    group: root
    mode: '644'

- name: Deploy certbot renew script
  ansible.builtin.template:
    src: renew.sh.j2
    dest: "{{ certbot_dir }}/renew.sh"
    owner: root
    group: root
    mode: '0755'

- name: Deploy certbot renew systemd service
  ansible.builtin.template:
    src: certbot-renew.service.j2
    dest: /etc/systemd/system/certbot-renew.service
    owner: root
    group: root
    mode: '0644'

- name: Deploy certbot renew systemd timer
  ansible.builtin.template:
    src: certbot-renew.timer.j2
    dest: /etc/systemd/system/certbot-renew.timer
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to apply new units
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start certbot renew timer
  ansible.builtin.systemd:
    name: certbot-renew.timer
    enabled: true
    state: started